### ISSUE TITLE
Click on tray icon does not open the app

### ISSUE THREAD

**Issue by jdvr** [ivelkov/teams-for-linux#12]
In some linux desktop environments click on tray icons does not open the app, we have tries it on Plasma, Unity and Cinnamon and we have problems on Plasma and Unity.

**Comment by jdvr** [comment]
I have created the #13 to solve this with an option that works on all desktops.

**Comment by jdvr** [comment]
Maybe this is related: https://github.com/electron/electron/issues/6773

**Comment by julian-alarcon** [comment]
Check this fork and star it! https://github.com/IsmaelMartinez/teams-for-linux It is currently supported!
Maybe these issue is not there.
