### ISSUE TITLE
Unable to share screen in a team meeting.

### ISSUE THREAD

**Issue by Shickmo** [ivelkov/teams-for-linux#15]
Hello,

Whenever I am trying to join a meeting the teams-for-linux app forces me to try and either download the client or open it in the web format. The problem is I need to share my screen and can't do that from the web interface as that has not been implemented yet. Is it possible to just let me share my screen from within the app?

Thanks in advance for your help.

**Comment by sgnls** [comment]
The app itself is a wrapper for the web-app, so until it's implemented there (which I'd doubt), it won't be possible.

**Comment by ivelkov** [comment]
Closing since we can't do pretty much anything.
