### ISSUE TITLE
Linux teams just stopped working  "Hmm. Your browser version isn't supported. Here's what works:"

### ISSUE THREAD

**Issue by yellabelly** [ivelkov/teams-for-linux#25]
Thanks for this Linux version of Teams it has been working very well for a while on Linux Mint 18.3 Sarah.
However it broke on 2 instances I use with text displaying 

![selection_265](https://user-images.githubusercontent.com/214279/33914286-6841e0d0-df95-11e7-9d24-b262f82d21a8.png)

**Comment by ivelkov** [comment]
Hi, try this https://github.com/ivelkov/teams-for-linux/releases/tag/v0.0.5

**Comment by obouchet** [comment]
Well your fix worked for a few hours but looks like Microsoft is refusing Chrome or even Firefox...
I tried different user-agent using your source code but the results is same whatever the agent.

**Comment by obouchet** [comment]
it works with this one on Fedora 27:

window.webContents.setUserAgent('Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0');

**Comment by yellabelly** [comment]
New version 0.0.5 is working well now on Mint 17.3, thanks Ivelin I owe you a beer next time you are in Dublin
