### ISSUE TITLE
Error icon on dash

### ISSUE THREAD

**Issue by riczup** [ivelkov/teams-for-linux#26]
![screenshot-20171213171740-65x239](https://user-images.githubusercontent.com/29820974/33949324-91f06b06-e029-11e7-884c-0c858c0bc4fd.png)
when lunch the program the icon on the dock isn't displayed correctly. if i pin on the dock the icon is show coorrectly but when lunch Teams the icon is duplicate and the icon isn't correctly.

**Comment by mickael83** [comment]
Same issue here using Fedora 27 with Gnome environment
![screenshot from 2018-01-31 12-33-20](https://user-images.githubusercontent.com/2827671/35623296-0085dcd4-0683-11e8-9f82-ca2b33ac8f07.png)

**Comment by BlueCase** [comment]
Problem is the "StartupWMClass": "teams" in the package.json.
Change that in /usr/share/applications/teams.desktop to teams-for-linux.

**Comment by riczup** [comment]
thanks, work!
