### ISSUE TITLE
Does not follow LC_TIME

### ISSUE THREAD

**Issue by Tux** [ivelkov/teams-for-linux#32]
I am not sure if this is "teams for Linux" or "electron", but my LC_TIME clearly states a 24-hour time notation, but my time-stamps in teams show as AM/PM (HATE!)
I know that teams does not support changing fonts, but if that were an option in teams for Linux, I'd be overjoyed!
``` sh
$ locale -ck LC_TIME | grep '^[dt]_'
d_t_fmt="%a %d %b %Y %R %Z"
d_fmt="%d-%m-%Y"
t_fmt="%R"
t_fmt_ampm="%H:%M:%S"
```

**Comment by ivelkov** [comment]
Hi, it's actually the microsoft teams browser application.

Check this out
![screenshot from 2018-02-27 12-54-21](https://user-images.githubusercontent.com/11614790/36724968-6f3a7898-1bbd-11e8-9881-adf44246e2a1.png)

It looks like the data format is dependent on the language option from the settings menu.
