### ISSUE TITLE
Notifications not working at all

### ISSUE THREAD

**Issue by lkrms** [ivelkov/teams-for-linux#37]
Thanks for your excellent work on this app.

I'm running 0.0.7 on Ubuntu 16.04 (lots of software installed but the desktop environment is pretty much  stock).

It's not clear if it's a Teams issue or is related to the teams-for-linux wrapper, but I'm yet to see any notifications of unread messages (or anything else) via the app. Nothing in the tray, launcher or via popup.

All of Teams' notification settings are correct (and Microsoft's own app delivers notifications as expected via supported platforms).

In the absence of any settings to enable / disable notifications, I'm guessing this is a bug? Happy to collect any data that might be needed to help investigate, but it would be good to know if others are having the same problem for starters.

In case it's relevant, I authenticate with Teams via an institutional SSO.

**Comment by ivelkov** [comment]
Hi,

There's an issue where if you minimize the teams window on an active chat and you receive messages on this chat, the messages you receive will be considered viewed at notifications are not going to pop up. 
I suspect that this is the problem you're having and I can't really fix it. Electron is using chrome and there's pretty much the same behaviour if you minimize the chrome browser.

HTH,
Ivelin

**Comment by lkrms** [comment]
Thanks for following up so quickly, Ivelin! I had wondered about this too -- can confirm that even after ensuring I'm focused on a different conversation, so incoming messages are definitely "unread", no notifications appear via any mechanism. Is there anything to check or override to ensure the app is "allowed" to raise notifications? Is it possible that browser-based notifications are disabled by an administrator (I only use Teams as a "user" for a particular client that doesn't like Slack).

**Comment by derricw** [comment]
I am having the same issue.  No notifications of any kind are working for me.  I even modified this project to work with outlook, and it also doesn't have working notifications.

**Comment by lkrms** [comment]
@derricw I wasn't able to get it to work at all. Now using Rambox instead -- it doesn't provide pop-up notifications for Teams either, but the tray icon changes when there's an unread message / notification in Teams.

**Comment by suatDotCom** [comment]
Hi everybody! This is simple solution in browser/index.js :laughing: 
 `npm install --save electron-notifications`

```
...
const notifier = require("electron-notifications");


function NotificationTrigger() {
    var notification = notifier.notify("Teams", {
      message: "Yeni Mesaj Var!",
      icon: iconPath,
      buttons: ["Dismiss"],
      vertical: true
});

    notification.on("clicked", function() {
      notification.close();
    });
  }
```
```
var hasNotification = false;
  document.addEventListener("DOMNodeInserted", function(e) {
    var toast = document.getElementById("toast-container");
    console.log(toast);
    if (toast) {
      if (hasNotification == false) NotificationTrigger();

      hasNotification = true;
    }
  });

document.addEventListener("DOMNodeRemoved", function() {
    hasNotification = false;
  });
```

**Comment by FSMaxB-divae** [comment]
I made a firefox webextension that intercepts notifications: https://github.com/FSMaxB/teams-wim

Feel free to copy my approach for intercepting notifications.

The way I do it is by intercepting the push notifications that Teams get's via HTTP and interpreting the content of the JSON response.

**Comment by nate-anderson** [comment]
@suatDotCom is the solution to add the code snippets provided to index.js?

**Comment by IsmaelMartinez** [comment]
Hi @nate-anderson @FSMaxB-divae  @suatDotCom @lkrms @derricw  and @ivelkov 

This project and the JamieMagee seem dead so, until they come back alive and I can merge back my changes, you can use and contribute in my branch.

https://github.com/IsmaelMartinez/teams-for-linux

Got notifications support. Nothing to fancy but works. I tried the solution by @suatDotCom but wasn't really working as there are so many things changing the dom.
