### ISSUE TITLE
Publish to AUR

### ISSUE THREAD

**Issue by colemickens** [ivelkov/teams-for-linux#4]
Would you be willing to publish to AUR?

**Comment by ivelkov** [comment]
Sure, I'll do that in the following week.
Thanks

**Comment by adamjameschristensen** [comment]
The university I work for has just moved from Slack to Teams. As an Arch Linux user, I'm happy to find this wrapper! I would also love to see it published in the AUR! Thanks for your work on this!

**Comment by neolectron** [comment]
ping ?

**Comment by ivelkov** [comment]
Hi, try this out - https://aur.archlinux.org/packages/teams-for-linux/

Sorry for the huge delay.
I'm a Fedora user and there was no incentive to work on this issue ;-)
