### ISSUE TITLE
White page after refresh

### ISSUE THREAD

**Issue by ragusa87** [ivelkov/teams-for-linux#7]
Hello,
First at all, thanks for this app, we are using teams at work and this app is very useful !

However, I got an annoying bug:
If I hit the refresh button, the page turns white and I can not see anything.
![image](https://cloud.githubusercontent.com/assets/1695207/24896307/966b1c78-1e94-11e7-9bf3-4f685f4059ed.png)
If I put the mouse on the left upper corner, I can se that I am on a link as the cursor changes. So the page looks loaded, but rendered as white.

I am using Ubuntu 16.10 on kernel 4.8.0-46-generic.

I got the same behavior if I close the window and open it from the notification panel.
Thanks for your help.

**Comment by higorcoliveira** [comment]
I got the same issue, after I logon on my MS enterprise account, a blank screen appears to me. I'm using Ubuntu 16.04.2 LTS 4.4.0-72-generic. Image attached.

![captura de tela de 2017-04-18 13 46 01](https://cloud.githubusercontent.com/assets/6370767/25142584/d08b775a-243d-11e7-812b-c3f752f14cd7.png)

Thanks.

**Comment by daniel-frank** [comment]
Same as @higorcoliveira in Ubuntu 16.04 4.4.0-72-generic.

**Comment by ivelkov** [comment]
Hi,

It's really chrome behind the scenes, so it would be a bit hard to see what's the exact issue.

You are going to get chrome devtools opened if you run teams like this.
`[ivelin@ivelin-laptop ~] $ WEB_DEBUG=1 teams`

Perhaps the console and/or the network could shed some light?

Thanks

**Comment by ragusa87** [comment]
Thanks for your answer,

Well, with the debug flag, and everything works as expected. I tried without it and it seems to work as well. I am not able to reproduce the bug for now. 

I will try to wait a while before clicking on the "refresh" button, maybe it has something to do with the session duration, I will keep you posted.

**Comment by IsmaelMartinez** [comment]
same as #9

**Comment by julian-alarcon** [comment]
Check this fork and star it! https://github.com/IsmaelMartinez/teams-for-linux It is currently supported!
Maybe these blank page issue is not there.

**Comment by IsmaelMartinez** [comment]
I believe the blank issue was related to ntlm authentication. That is sorted in the fork
